version: '3.5'
services:
  nginx:
    image: nginx
    container_name: f_nginx
    restart: always
    ports:
      - "81:8788"
      - "82:8792"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - postgresql:postgresql
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: '512M'
  
  postgresql:
      image: postgres:14.5
      command: -c 'maintenance_work_mem=512MB' -c 'shared_buffers=512MB' -c 'max_connections=550' -p 5707
      restart: always
      expose:
        - "5707" # Publishes 5707 to other containers but NOT to host machine
      ports:
        - "5707:5707"
      volumes:
        - ./backup:/home
        # - /mnt/e/Workspace/ttek/backup-database/backup:/backup
      # networks:
      #   - postgresql
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=8caf799b2f81e4ed7b51fd2b0bb1292fd8062fa2aae268ec54d6740710d41970
        - POSTGRES_DB=family
        - LANG=en_US.UTF-8
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 256M
          reservations:
            cpus: '0.25'
            memory: 128M