nginx:
  image: nginx:1.15.3-alpine
  ports:
    - "80:8788"
    - "81:9770"
    - "443:443"
  restart: on-failure
  volumes:
    - ./config/nginx:/etc/nginx/conf.d
  links:
    - api:api
    # - files:files
    - webapp:webapp
    - webappsale:webappsale
api:
  build: ../family-server
  restart: on-failure
  volumes:
    - ../family-server:/usr/src/app1

webappsale:
  build: ../sale-dav-front-end
  volumes:
    - ./:/usr/src/app3
  restart: on-failure

<<<<<<< HEAD
  workingapi:
    build:
      context: ../working-server
      shm_size: '512M'
    container_name: working_api
    volumes:
      - ../working-server:/usr/src/app1
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    # networks:
    #   - db

  webapp:
    build: ../family-dashboard
    container_name: f_webapp
    volumes:
      - ../family-dashboard:/usr/src/app2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M

  mobileapp:
    build: ../mobilewebapp
    container_name: f_mobileapp
    volumes:
      - ../mobilewebapp:/usr/src/app2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M
=======
webapp:
  build: ../family-dashboard
  volumes:
    - ./:/usr/src/app2
  restart: on-failure
>>>>>>> 34579daa7ba64791552ae689b225bc73ac2ba702
