version: '3.5'
services:
  nginx:
    image: nginx:1.15.3-alpine
    ports:
      - "81:8788"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - api:api
      - webapp:webapp
      - postgresql:postgresql
  
  postgresql:
      image: postgres:10
      command: -c 'maintenance_work_mem=512MB' -c 'shared_buffers=512MB' -c 'max_connections=550' -p 5707
      restart: always
      expose:
        - "5707" # Publishes 5707 to other containers but NOT to host machine
      ports:
        - "5707:5707"
      volumes:
        - ./backup:/home
        # - /mnt/e/Workspace/ttek/backup-database/backup:/backup
      # networks:
      #   - postgresql
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=8caf799b2f81e4ed7b51fd2b0bb1292fd8062fa2aae268ec54d6740710d41970
        - POSTGRES_DB=family
        - LANG=en_US.UTF-8

  api:
    build: ../family-server
    volumes:
      - ../family-server:/usr/src/app1
    links:
      - "postgresql:database"
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5707
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8caf799b2f81e4ed7b51fd2b0bb1292fd8062fa2aae268ec54d6740710d41970
      - POSTGRES_DB=family
      - LANG=en_US.UTF-8
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - postgresql
    # networks:
    #   - db

  webapp:
    build: ../family-dashboard
    volumes:
      - ../family-dashboard:/usr/src/app2
