nginx:
  image: nginx:1.15.3-alpine
  ports:
    - "80:8788"
    - "443:443"
  restart: on-failure
  volumes:
    - ./config/nginx:/etc/nginx/conf.d
  links:
    - api:api
    # - files:files
    - webapp:webapp
api:
  build: ../family-server
  restart: on-failure
  volumes:
    - ../family-server:/usr/src/app1
# files:
#   build: ../family-server
#   volumes:
#     - ../family-server:/usr/src/app1
webapp:
  build: ../family-dashboard
  volumes:
    - ./:/usr/src/app2
  restart: on-failure
