version: '3.5'
services:
  nginx:
    image: nginx
    container_name: f_nginx
    restart: always
    ports:
      - "81:8788"
      - "82:8792"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - api:api
      - workingapi:workingapi
      # - webapp:webapp
      # - mobileapp:mobileapp
      - postgresql:postgresql
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: '512M'
  
  postgresql:
      image: postgres:14.5
      command: -c 'maintenance_work_mem=512MB' -c 'shared_buffers=512MB' -c 'max_connections=550' -p 5707
      restart: always
      expose:
        - "5707" # Publishes 5707 to other containers but NOT to host machine
      ports:
        - "5707:5707"
      volumes:
        - ./backup:/home
        # - /mnt/e/Workspace/ttek/backup-database/backup:/backup
      # networks:
      #   - postgresql
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=8caf799b2f81e4ed7b51fd2b0bb1292fd8062fa2aae268ec54d6740710d41970
        - POSTGRES_DB=family
        - LANG=en_US.UTF-8
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 256M
          reservations:
            cpus: '0.25'
            memory: 128M
  postgresclv:
        image: postgres:14.5
        command: -c 'maintenance_work_mem=512MB' -c 'shared_buffers=512MB' -c 'max_connections=550' -p 55432
        restart: always
        expose:
          - "55432" # Publishes 55432 to other containers but NOT to host machine
        ports:
          - "55432:55432"
        volumes:
          - ./backup:/home
          # - /mnt/e/Workspace/ttek/backup-database/backup:/backup
          #
        # networks:
        #   - postgresql
        environment:
          - POSTGRES_USER=us_fwd_dev
          - POSTGRES_PASSWORD=Cyber2021
          - POSTGRES_DB=us_fwd_dev
          - LANG=en_US.UTF-8
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 256M
            reservations:
              cpus: '0.25'
              memory: 128M
  api:
    build:
      context: ../family-server
      shm_size: '512M'
    container_name: f_api
    restart: always
    ports:
        - "8789:8789"
    volumes:
      - ../family-server:/usr/src/f_api
      - ../family-server/emails/HSBC:/usr/src/app1/emails/HSBC
      - ../family-server/emails/VIB:/usr/src/app1/emails/VIB
      - ../family-server/emails/SCBANK:/usr/src/app1/emails/SCBANK
    links:
      - "postgresql:database"
    environment:
      #- DB_HOST=postgresql (for docker)
      # - DB_PORT=5707
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=8caf799b2f81e4ed7b51fd2b0bb1292fd8062fa2aae268ec54d6740710d41970
      # - POSTGRES_DB=family
      - LANG=en_US.UTF-8
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - postgresql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    # networks:
    #   - db
  # mobileapp:
  #   build: ../mobilewebapp
  #   container_name: f_mobileapp
  #   restart: always
  #   ports:
  #       - "8792:8792"
  #   # volumes:
  #   #   - ../mobilewebapp:/usr/src/f_mobileapp
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 1024M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 128M
  workingapi:
    build:
      context: ../working-server
      shm_size: '512M'
    container_name: working_api
    restart: always
    ports:
        - "9789:9789"
    volumes:
      - ../working-server:/usr/src/f_working_api
    environment:
        - PORT=9789
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    # networks:
    #   - db
  # websocket:
  #   build:
  #     context: ../family-websocket
  #     shm_size: '512M'
  #   container_name: f_websocket
  #   restart: always
  #   ports:
  #       - "5789:5789"
  #   volumes:
  #     - ../family-websocket:/usr/src/f_websocket
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 256M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 128M
    # networks:
    #   - db

  # webapp:
  #   build: ../family-dashboard
  #   container_name: f_webapp
  #   restart: always
  #   ports:
  #       - "8790:8790"
  #   volumes:
  #     - ../family-dashboard:/usr/src/f_webapp
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 1024M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 128M
  
          
