version: "3.5"
services:
  postgresql:
    image: postgres:10
    command: -c 'maintenance_work_mem=512MB' -c 'shared_buffers=512MB' -c 'max_connections=550'
    restart: always
    ports:
      - 5707:5432
    volumes:
      - ./backup:/home
      # - /mnt/e/Workspace/ttek/backup-database/backup:/backup
    networks:
      - postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8caf799b2f81e4ed7b51fd2b0bb1292fd8062fa2aae268ec54d6740710d41970
      - POSTGRES_DB=family
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6g
      placement:
        constraints:
          - node.labels.postgresql==true
    logging:
      driver: "json-file"
      options:
        max-size: "5MB"
        max-file: "1"

networks:
  postgresql:
    driver: bridge

# volumes:
#   postgres10.5:
